// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1ptAlIeFb7-GJkJ0_BEajbCsOFH6gM98',
    appId: '1:322972685596:web:f81a1cde1ee75f731ed6d9',
    messagingSenderId: '322972685596',
    projectId: 'inclasschallenge',
    authDomain: 'inclasschallenge.firebaseapp.com',
    storageBucket: 'inclasschallenge.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVto5qjYSYVFtZCUwirUmkJK_X0z7P7HI',
    appId: '1:322972685596:android:8300b5f1903ab5461ed6d9',
    messagingSenderId: '322972685596',
    projectId: 'inclasschallenge',
    storageBucket: 'inclasschallenge.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_FHRRTgYKwpDmNVQZpy_B1z3UwjMHuvA',
    appId: '1:322972685596:ios:b407c0590d435ecd1ed6d9',
    messagingSenderId: '322972685596',
    projectId: 'inclasschallenge',
    storageBucket: 'inclasschallenge.firebasestorage.app',
    iosBundleId: 'com.example.geoWeatherLoggerApp',
  );
}
